bindAddress: ':53'
debugHTTPAddress: '127.0.0.1:5555'
dohEnabled: false
primaryDNS:
  - name: dns1
    address: '119.29.29.29'
    protocol: tcp
    socks5Address:
    timeout: 2
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: dns2
    address: '114.114.114.114'
    protocol: tcp
    socks5Address:
    timeout: 2
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
alternativeDNS:
  - name: google8888
    address: '8.8.8.8:53'
    protocol: udp
    socks5Address:
    timeout: 3
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: google8844
    address: '8.8.4.4:53'
    protocol: udp
    socks5Address:
    timeout: 3
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: true
whenPrimaryDNSAnswerNoneUse: alternativeDNS
ipNetworkFile:
  primary: '.\\china_ip_list.txt'
  alternative:
domainFile:
  primary: '.\\china_list.txt'
  alternative: '.\\gfw_list.txt'
  matcher: suffix-tree
hostsFile:
  hostsFile: 'C:\\Windows\\System32\\drivers\\etc\\hosts'
  finder: full-map
minimumTTL: 60
domainTTLFile:
cacheSize: 1024
cacheRedisUrl:
cacheRedisConnectionPoolSize:
rejectQType:
  - 255

